CREATE TABLE IF NOT EXISTS servers (
    id INT PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    maintenance BOOLEAN NOT NULL DEFAULT FALSE,
    overloaded BOOLEAN NOT NULL DEFAULT FALSE,
    is_new BOOLEAN NOT NULL DEFAULT FALSE,
    character_count SMALLINT NOT NULL DEFAULT 0
);
