CREATE TABLE IF NOT EXISTS characters (
    id BIGSERIAL PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    slot SMALLINT NOT NULL,
    name VARCHAR(32) UNIQUE NOT NULL,
    model INT NOT NULL DEFAULT 0,
    level SMALLINT NOT NULL DEFAULT 1,
    general_handler INT NOT NULL DEFAULT 0,
    partner_handler INT NOT NULL DEFAULT 0,

    -- Position
    current_x INT NOT NULL DEFAULT 0,
    current_y INT NOT NULL DEFAULT 0,
    current_z REAL NOT NULL DEFAULT 0.0,
    current_map_id SMALLINT NOT NULL DEFAULT 0,
    partner_current_x INT NOT NULL DEFAULT 0,
    partner_current_y INT NOT NULL DEFAULT 0,
    partner_current_z REAL NOT NULL DEFAULT 0.0,

    -- State
    state SMALLINT NOT NULL DEFAULT 0,
    channel SMALLINT NOT NULL DEFAULT 0,
    current_condition SMALLINT NOT NULL DEFAULT 0,
    previous_condition SMALLINT NOT NULL DEFAULT 0,
    xgauge SMALLINT NOT NULL DEFAULT 0,
    xcrystals SMALLINT NOT NULL DEFAULT 0,
    bits BIGINT NOT NULL DEFAULT 0,
    inventory_bits BIGINT NOT NULL DEFAULT 0,
    server_experience INT NOT NULL DEFAULT 0,
    premium INT NOT NULL DEFAULT 0,
    silk INT NOT NULL DEFAULT 0,
    membership_seconds BIGINT NOT NULL DEFAULT 0,
    initial_packet_sent_once BOOLEAN NOT NULL DEFAULT FALSE,
    riding BOOLEAN NOT NULL DEFAULT FALSE,

    -- Partner (Digimon)
    partner_digimon_id INT NOT NULL DEFAULT 0,
    partner_name VARCHAR(64) NOT NULL DEFAULT '',
    partner_level SMALLINT NOT NULL DEFAULT 1,
    partner_model INT NOT NULL DEFAULT 0,
    partner_current_type INT NOT NULL DEFAULT 0,
    partner_max_level SMALLINT NOT NULL DEFAULT 1,
    partner_hp INT NOT NULL DEFAULT 100,
    partner_ds INT NOT NULL DEFAULT 100,
    partner_current_hp INT NOT NULL DEFAULT 100,
    partner_current_ds INT NOT NULL DEFAULT 100,
    partner_exp BIGINT NOT NULL DEFAULT 0,

    -- Complex nested data stored as JSONB
    inventory JSONB NOT NULL DEFAULT '{"items":[],"size":0,"bits":0}',
    warehouse JSONB NOT NULL DEFAULT '{"items":[],"size":0,"bits":0}',
    extra_inventory JSONB NOT NULL DEFAULT '{"items":[],"size":0,"bits":0}',
    account_warehouse JSONB,
    seal_list JSONB NOT NULL DEFAULT '{"seals":[]}',
    guild_snapshot JSONB,
    xai_snapshot JSONB,
    active_buffs JSONB NOT NULL DEFAULT '[]',
    friends JSONB NOT NULL DEFAULT '[]',
    foes JSONB NOT NULL DEFAULT '[]',
    friended_character_ids JSONB NOT NULL DEFAULT '[]',
    map_regions JSONB NOT NULL DEFAULT '[]',
    equipment JSONB NOT NULL DEFAULT '{}',
    digivice JSONB NOT NULL DEFAULT '{}',
    daily_reward JSONB NOT NULL DEFAULT '{}',
    attendance JSONB NOT NULL DEFAULT '{}',
    available_channels JSONB NOT NULL DEFAULT '[{"channel":0,"load":1}]',
    evolutions JSONB NOT NULL DEFAULT '[]',

    UNIQUE(account_id, slot)
);
